[package]
name = "heap-view"
version = "0.1.0"
authors = ["Erich Gerhard Ess <erich.g.ess@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
